{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "auto-delete-admission.serviceAccountName" . }}
  labels:
{{ include "auto-delete-admission.labels" . | indent 4 }}
{{- end -}}
